spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: education-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
          zkNodes: education-kafka-zookeeper:2181
      bindings:
        class-topic:
          destination: class.topic
          contentType: application/json
          consumer:
            headerMode: raw

eureka:
  client:
    enabled: false
